name: BossLand
main: io.hotmail.com.jacob_vejvoda.BossLand.BossLand
version: 0.6
api-version: 1.16
author: Eliminator
softdepend: [WorldGuard]

commands:
  bossland:
    aliases: [bl]
    description: Base Boss Land command.
    usage: /<command>
    permission: bl.cmds
    permission-message: You don't have <permission>