name: BossLand
main: io.hotmail.com.jacob_vejvoda.BossLand.BossLand
version: ${project.version}
api-version: 1.16
authors: [Eliminator, Steve-Tech]
softdepend: [WorldGuard]
commands:
  bossland:
    aliases: [bl]
    description: Base Boss Land command
    usage: /<command>
    permission: bl.cmds
    permission-message: You don't have <permission>
permissions:
  bl.cmds:
    description: Base Boss Land permission
    default: op