# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Create Pre-release

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Short SHA
        id: sha_short
        run: echo ::set-output name=sha_short::$(git rev-parse --short=7 ${{ github.sha }})

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'


      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        env:
          SHORTSHA: ${{ steps.sha_short.outputs.sha_short }}
        run: mvn -B package --file pom.xml -Drevision=$SHORTSHA -Djar.finalName=$SHORTSHA

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHORTSHA: ${{ steps.sha_short.outputs.sha_short }}
        with:
          tag_name: ${{ env.SHORTSHA }}
          release_name: Release ${{ env.SHORTSHA }}
          draft: false
          prerelease: true

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHORTSHA: ${{ steps.sha_short.outputs.sha_short }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: 'target/${{ env.SHORTSHA }}.jar'
          asset_name: '${{ github.event.repository.name }}-${{ env.SHORTSHA }}.jar'
          asset_content_type: application/java-archive
